//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file was automatically generated by RisohEditor.
// WinHier_res.rc

#define IDC_STATIC                          -1

#define IDC_TARGET                          100

#define IDD_MAIN                            100
#define IDD_PROPERTIES                      101

#define IDI_MAIN                            100
#define IDI_NULL                            101

#define ID_WINDOW_CHOOSED                   100
#define ID_PROP                             101
#define ID_MESSAGES                         102

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    100
        #define _APS_NEXT_COMMAND_VALUE     103
        #define _APS_NEXT_CONTROL_VALUE     1000
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
