//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file was automatically generated by RisohEditor.
// WinHier_res.rc

#define IDC_STATIC                          -1

#define IDC_TARGET                          100

#define IDD_MAIN                            100
#define IDD_PROPERTIES                      101

#define IDI_MAIN                            100
#define IDI_NULL                            101

#define IDS_SAVEAS                          100
#define IDS_FILTER                          101
#define IDS_CANTSAVE                        102
#define IDS_TXTNAME                         103

#define ID_WINDOW_CHOOSED                   100
#define ID_PROP                             101
#define ID_MESSAGES                         102
#define ID_COPYASTEXT                       103
#define ID_COPYHWND                         104
#define ID_COPYTEXT                         105
#define ID_COPYCLASSNAME                    106
#define ID_SHOW                             107
#define ID_HIDE                             108
#define ID_DESTROY                          109
#define ID_BLINK                            110

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    100
        #define _APS_NEXT_COMMAND_VALUE     111
        #define _APS_NEXT_CONTROL_VALUE     1000
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
